### ISSUE TITLE
issue running jupyter notebook analyzing_artemis.ipynb

### ISSUE THREAD

**Issue by hlsafin** [optas/artemis#1]
![image](https://user-images.githubusercontent.com/36808133/112695959-5722d200-8e5b-11eb-823d-a46d162f5e1b.png)
os=windows
python=3.6

I can't seem to run the first line in  analyzing_artemis.ipynb notebook. Not sure what occured. Thank you!

**Comment by optas** [comment]
Hi! Thanks for trying things around. I believe it is either that you did not pip install it (please see installation step "pip install -e .") _or_ you did not add artemis (this package) in your PYTHON-PATH (there should be plenty of how to do this on windows online).
