### ISSUE TITLE
Trying to preprocess the artemis data

### ISSUE THREAD

**Issue by hlsafin** [optas/artemis#2]
C:\Users\safin\Miniconda3\envs\artemis\python.exe C:/Users/safin/artemis/artemis/scripts/preprocess_artemis_data.py
{'automatic_spell_check': True,
 'group_gt_anno': True,
 'min_word_freq': 0,
 'n_train_examples': None,
 'preprocess_for_deep_nets': False,
 'random_seed': 2021,
 'raw_artemis_data_csv': './ola_dataset_release_v0.csv',
 'save_out_dir': './',
 'split_loads': [0.85, 0.05, 0.1],
 'too_high_repetition': -1,
 'too_long_utter_prc': 100,
 'too_short_len': 0}
5000 annotations were loaded
Using a 0.85,0.05,0.1 for train/val/test purposes
Traceback (most recent call last):
  File "C:/Users/safin/artemis/artemis/scripts/preprocess_artemis_data.py", line 246, in <module>
    df, vocab, missed_tokens = preprocess(args)
  File "C:/Users/safin/artemis/artemis/scripts/preprocess_artemis_data.py", line 182, in preprocess
    missed_tokens = tokenize_and_spell(df, glove_file, freq_file, nltk.word_tokenize, spell_check=args.automatic_spell_check)
  File "c:\users\safin\artemis\artemis\language\basics.py", line 66, in tokenize_and_spell
    golden_vocabulary = load_glove_pretrained_embedding(glove_file, only_words=True, verbose=True)
  File "c:\users\safin\artemis\artemis\neural_models\word_embeddings.py", line 74, in load_glove_pretrained_embedding
    for line in f_in:
  File "C:\Users\safin\Miniconda3\envs\artemis\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3515: character maps to <undefined>
SymSpell spell-checker loaded: True
Loading glove word embeddings.

OS: Windows 10
python: 3.6
I have the data artemis dataset in the directory, and just ran everything in the default setting and ran into UnicodeDecodeError error.

**Comment by optas** [comment]
Hi! Excellent question! I believe this has to do with the fact that some _filenames_ of the .jpgs of the widely used version of the WikiArt; contain some non-unicode characters. I will update here 2-3 lines of code you can use to address this issue, this week. Given some time pressure; please filter those images out for the moment being. I doubt there are more than 20 files with such an issue. (you can also try to rename those few by removing/deleting manually the non-unicode character - which is -likely- what I did when I processed the WikiArt dataset more than a year ago).

**Comment by hlsafin** [comment]
![image](https://user-images.githubusercontent.com/36808133/113017415-694b8b80-914d-11eb-9f40-a19d41edb1c4.png)
so I did this, for the time being, I added errors='ignore', I also tried encoding='utf-8'. 
At any case, I get this error showing up at the bottom
![image](https://user-images.githubusercontent.com/36808133/113017697-bc254300-914d-11eb-9239-5449c270a062.png)
