### ISSUE TITLE
Can't find artemis_preprocessed.csv and rescaled_max_size_to_600px_same_aspect_ratio on repo?

### ISSUE THREAD

**Issue by texturejc** [optas/artemis#3]
Hi, in the notebook for the basic linguistic, emotion & art-oriented analysis of the ArtEmis dataset, you are required to have the data specified these filepaths downloaded. But I can't seem to find them anywhere on the repo? Can you advise here please? Thanks.

```
artemis_preprocessed_csv = '/home/optas/DATA/OUT/artemis/preprocessed_data/for_analysis/artemis_preprocessed.csv'
wikiart_img_dir = '/home/optas/DATA/Images/Wiki-Art/rescaled_max_size_to_600px_same_aspect_ratio'
```

**Comment by optas** [comment]
Hi! These are "input" files/folders that refer to data that you should have to your local machine. 

First, the .csv contains the preprocessed ArtEmis data. The ArtEmis dataset can be downloaded upon signing the TOS (https://forms.gle/7eqiRgb764uTuexd7). After you download it use the scripts/preprocess_artemis_data.py to do the preprocessing which will create for you the .csv

Second, the other is the top-dir where you have stored the WikiArt dataset (that is the images of the artworks). You can download this dataset from many places (just google wikiArt dataset).  If you have problems finding it; please let me know.

Best,
Panos

**Comment by texturejc** [comment]
Great, clarifies the issue nicely––thanks!
