### ISSUE TITLE
How can I download the data?

### ISSUE THREAD

**Issue by cenjinglun** [optas/artemis#9]
Is my approach the right way?

![image](https://user-images.githubusercontent.com/44342283/145912001-d9df5b8b-0739-4346-ab7a-f4749194ca80.png)

![image](https://user-images.githubusercontent.com/44342283/145912129-e880d31c-d46d-4635-ad95-ae52f31925f4.png)

**Comment by cenjinglun** [comment]
The problem was solved.

**Comment by yiren-jian** [comment]
For anyone who is also looking for wikiart images, I use the one from here: https://github.com/cs-chan/ArtGAN/tree/master/WikiArt%20Dataset
